version: 1.0.{build}
clone_depth: 3
skip_tags: true

configuration:

- Release

platform:

- Win32


image:

- Visual Studio 2017


environment:

  my_variable:

    secure: 1yit9q4kA36G3TjQw34DeHhFBVjc/JVNPqLC01rX3dGNAEi1jXMXSkgdDlO9q76Q

  matrix:

  - BUILD_MODE: MSBuild

# Disable build through solution file
build: off

# Build through commands in script below
test_script:
  cmake .

  msbuild /t:Build  D0.vcxproj


deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 1yit9q4kA36G3TjQw34DeHhFBVjc/JVNPqLC01rX3dGNAEi1jXMXSkgdDlO9q76Q # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only


