version: 1.0.{build}
clone_depth: 3
skip_tags: true

configuration:

- Debug
- Release

platform:

- Win32
- x64

image:

- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013

environment:

  matrix:

  - BUILD_MODE: MSBuild

# Disable build through solution file
build: off

# Build through commands in script below
test_script:
  parallel: true                  # enable MSBuild parallel builds
  project: Practice.sln      # path to Visual Studio solution or project

- ps: >-
    .\Practice.exe