version: 1.0.{build}
clone_depth: 3
skip_tags: true

configuration:

- Release

platform:

- Win32


image:

- Visual Studio 2017


environment:

  my_variable:

    secure: 1yit9q4kA36G3TjQw34DeHhFBVjc/JVNPqLC01rX3dGNAEi1jXMXSkgdDlO9q76Q

  matrix:

  - BUILD_MODE: MSBuild

# Disable build through solution file
build: off

# Build through commands in script below
test_script:
  cmake .

  msbuild /t:Build  D0.vcxproj

  git config --global user.email "992061851@qq.com"

  git config --global user.name "EHie"

  git add Release/*

  git commit -m "Complier"

  git tag -a v{build} -m "release-{build}"

  git push origin v{build}


