version: 1.0.{build}
clone_depth: 3
skip_tags: true

configuration:

- Release

platform:

- x64

image:

- Visual Studio 2019

artifacts:
  - path: x64\Debug\MagicalTower.exe
    name: MagicalTower

  - path: img
    name: img
    type: zip


environment:

  my_variable:

    secure: 1yit9q4kA36G3TjQw34DeHhFBVjc/JVNPqLC01rX3dGNAEi1jXMXSkgdDlO9q76Q

  matrix:

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x64
    qt: 5.13
    releaseName: qt512_vs2015_x64

#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    platform: win32
#    qt: 5.13
#    releaseName: qt512_vs2017_x64

before_build:
#  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set msvc=msvc2015
#  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set vs=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
  set msvc=msvc2019
  set vs=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build
  - if "%platform%"=="x86" set QTDIR=C:\Qt\%qt%\%msvc%
  - if "%platform%"=="x64" set QTDIR=C:\Qt\%qt%\%msvc%_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - if "%platform%"=="x86" set vcvarsall=%vs%\vcvarsall.bat
  - if "%platform%"=="x64" set vcvarsall=%vs%\vcvarsall.bat
  - if "%platform%"=="x86" call "%vcvarsall%" x86
  - if "%platform%"=="x64" call "%vcvarsall%" x64
build_script:
  - qmake
  - nmake
after_build:
  - if "%APPVEYOR_REPO_TAG%"=="true" windeployqt x64\Debug\MagicalTower.exe --qmldir %QTDIR%\qml

#test_script:
  #cd MagicalTower

  #msbuild MagicalTower.sln


deploy:
  release: MagicalTower-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 1yit9q4kA36G3TjQw34DeHhFBVjc/JVNPqLC01rX3dGNAEi1jXMXSkgdDlO9q76Q # encrypted token from GitHub
  artifact: img;MagicalTower
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only


notifications:
  - provider: Email
    to:
      - 992061851@qq.com
    on_build_success: true
    on_build_failure: true
