version: 1.0.{build}
clone_depth: 3
skip_tags: true

configuration:

- Release

platform:

- x64

image:

- Visual Studio 2019

artifacts:
  - path: x64\Debug\MagicalTower.exe
    name: MagicalTower

  - path: img
    name: img
    type: zip


environment:

  my_variable:

    secure: 1yit9q4kA36G3TjQw34DeHhFBVjc/JVNPqLC01rX3dGNAEi1jXMXSkgdDlO9q76Q

  matrix:

  - BUILD_MODE: MSBuild

# Disable build through solution file
build: off

# Build through commands in script below
#cmake .
#msbuild /t:Build  Demo.vcxproj
#cd Release
#Demo.exe

test_script:
  cd MagicalTower

  msbuild MagicalTower.sln


deploy:
  release: Demo-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 1yit9q4kA36G3TjQw34DeHhFBVjc/JVNPqLC01rX3dGNAEi1jXMXSkgdDlO9q76Q # encrypted token from GitHub
  artifact: img;MagicalTower 
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only


notifications:
  - provider: Email
    to:
      - 992061851@qq.com
    on_build_success: true
    on_build_failure: true
