version: 1.0.{build}
clone_depth: 3
skip_tags: true

configuration:

- Release

platform:

- Win32


image:

- Visual Studio 2017


environment:

  matrix:

  - BUILD_MODE: MSBuild

# Disable build through solution file
build: off

# Build through commands in script below
test_script:
  cmake .

  msbuild /t:Build  D0.sln

  msbuild /t:Build  D0.vcxproj

