version: 1.0.{build}
clone_depth: 3
skip_tags: true

configuration:

- Debug
- Release

platform:

- Win32
- x64

image:

- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013

environment:

  matrix:

  - BUILD_MODE: MSBuild

# Disable build through solution file
build: off

# Build through commands in script below
test_script:
  cmake .
<<<<<<< HEAD

  msbuild /t:Build /p:platform="$env:platform" /p:configuration="$env:configuration" D0.sln

  msbuild /t:Build /p:platform="$env:platform" /p:configuration="$env:configuration" D0.vcxproj
=======
  
  msbuild /t:Build /p:platform="$env:platform" /p:configuration="$env:configuration" D0.sln
  
  msbuild /t:Build /p:platform="$env:platform" /p:configuration="$env:configuration" D0.vcxproj
  
>>>>>>> 85b18a8d512ae9b6470a163f1b0c055721802e0e
